# Generated by Django 3.0.5 on 2023-03-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='content',
            new_name='Wiadomość',
        ),
    ]
